# Generated by Django 5.1.1 on 2024-10-31 14:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program_name", models.CharField(max_length=100)),
                ("program_code", models.CharField(max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("accepted", models.BooleanField(default=False)),
                ("groups", models.ManyToManyField(to="auth.group")),
            ],
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "hospital_id",
                    models.CharField(
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Hospital ID must be 3-5 characters, capital letters and/or numbers.",
                                regex="^[A-Za-z0-9]{3,5}$",
                            )
                        ],
                    ),
                ),
                (
                    "hospital_name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Hospital name can only contain letters and numbers.",
                                regex="^[A-Za-z0-9 -]+$",
                            )
                        ],
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="City name can only contain letters.",
                                regex="^[A-Za-z ]*$",
                            )
                        ],
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="State must be 2 capital letters or empty.",
                                regex="^[A-Za-z]{0,2}$",
                            )
                        ],
                    ),
                ),
                ("latitude", models.CharField(max_length=11)),
                ("longitude", models.CharField(max_length=12)),
                (
                    "faa_identifier",
                    models.CharField(
                        blank=True,
                        max_length=4,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="FAA Identifier can only contain capital letters and numbers.",
                                regex="^[A-Za-z0-9 ]*$",
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("airport", models.BooleanField()),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospitals",
                        to="docs_app.programinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
